//! Kyutai TTS static architecture config.
//!
//! Mirrors the published `config.json` for
//! [`kyutai/tts-1.6b-en_fr`](https://huggingface.co/kyutai/tts-1.6b-en_fr):
//!
//! ```text
//! card        = 2048   // audio vocab
//! n_q = dep_q = 32     // codebooks (all generated by the depth transformer)
//! dim         = 2048   // backbone d_model
//! text_card   = 8000   // text vocab (SPM 8k en/fr/audio)
//! num_heads   = 16
//! num_layers  = 16
//! context     = 500
//! hidden_scale = 4.125
//! gating       = "silu"
//! norm         = "rms_norm_f32"
//! positional_embedding = "rope"
//!
//! depformer_dim                 = 1024
//! depformer_num_heads           = 16
//! depformer_num_layers          = 4
//! depformer_dim_feedforward     = 3072
//! depformer_multi_linear        = true
//! depformer_pos_emb             = "none"
//! depformer_weights_per_step    = true
//! depformer_low_rank_embeddings = 128
//!
//! cross_attention      = true   // speaker_wavs (512-D, cross)
//! demux_second_stream  = true
//!
//! tts_config = { audio_delay: 1.28s, second_stream_ahead: 2 }
//! ```

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// Positional embedding style for a transformer stack.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PositionalEmbedding {
    Rope,
    Sin,
    None,
}

/// Per-stack transformer config (backbone or depth).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransformerConfig {
    pub d_model: usize,
    pub num_heads: usize,
    pub num_layers: usize,
    pub dim_feedforward: usize,
    pub causal: bool,
    pub context: usize,
    pub max_period: usize,
    pub positional_embedding: PositionalEmbedding,
}

/// Depth decoder config (`DepFormer`) — generates the 32 audio codebooks for one frame.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DepFormerConfig {
    pub dim: usize,
    pub num_heads: usize,
    pub num_layers: usize,
    pub dim_feedforward: usize,
    pub multi_linear: bool,
    pub positional_embedding: PositionalEmbedding,
    /// Per-step weights for input/output linears + transformer layers.
    pub weights_per_step: bool,
    /// Sharing schedule for `weights_per_step` heads (one entry per codebook).
    pub weights_per_step_schedule: Vec<usize>,
    /// Low-rank decomposition rank for codebook embeddings (`emb -> low_rank -> dim`).
    pub low_rank_embeddings: usize,
}

/// Tensor conditioner (e.g. pre-computed `speaker_wavs` embedding).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TensorConditioner {
    pub dim: usize,
}

/// Look-up-table conditioner (e.g. CFG strength bin → embedding).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LutConditioner {
    pub n_bins: usize,
    pub dim: usize,
    pub tokenizer: String,
    pub possible_values: Vec<String>,
}

/// Conditioner payload — discriminated by `type` in JSON.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum ConditionerKind {
    Tensor { tensor: TensorConditioner },
    Lut { lut: LutConditioner },
}

/// Single named conditioner (e.g. `"speaker_wavs"`, `"cfg"`, `"control"`).
pub type ConditionerConfig = ConditionerKind;

/// Fuser: how each conditioner is mixed into the backbone.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FuserConfig {
    pub cross_attention_pos_emb: bool,
    pub cross_attention_pos_emb_scale: f32,
    /// Names of `sum`-fused conditioners (added to the backbone hidden state).
    pub sum: Vec<String>,
    /// Names of `prepend`-fused conditioners.
    pub prepend: Vec<String>,
    /// Names of `cross`-attention conditioners.
    pub cross: Vec<String>,
}

/// TTS-specific runtime config (audio shift, streaming offsets).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TtsConfig {
    /// Seconds the audio stream lags the text stream (1.28 s ⇒ 16 frames at 12.5 Hz).
    pub audio_delay: f32,
    /// Frames the second (demuxed) stream leads the primary.
    pub second_stream_ahead: usize,
}

/// Full Kyutai TTS architecture preset (mirrors HF `config.json`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KyutaiTtsConfig {
    // backbone (`dim`, `num_heads`, `num_layers`, `context`, `max_period`)
    pub dim: usize,
    pub num_heads: usize,
    pub num_layers: usize,
    pub hidden_scale: f32,
    pub causal: bool,
    pub context: usize,
    pub max_period: usize,
    pub gating: String,
    pub norm: String,
    pub positional_embedding: PositionalEmbedding,

    // codebook / vocab
    /// Audio vocab size per codebook (`card`).
    pub card: usize,
    /// Total RVQ codebooks (`n_q`).
    pub n_q: usize,
    /// Codebooks generated by the depth transformer (`dep_q`).
    pub dep_q: usize,
    /// Per-codebook delays (length `n_q + 1`: text + audio streams).
    pub delays: Vec<i32>,
    pub text_card: usize,
    pub text_card_out: Option<usize>,
    pub existing_text_padding_id: u32,

    // depformer
    pub depformer: DepFormerConfig,

    // multistream / cross-attention
    pub demux_second_stream: bool,
    pub cross_attention: bool,

    pub conditioners: BTreeMap<String, ConditionerConfig>,
    pub fuser: FuserConfig,

    pub tts_config: TtsConfig,
}

impl KyutaiTtsConfig {
    /// Static preset for `kyutai/tts-1.6b-en_fr` (matches the published `config.json`).
    pub fn v1_6b_en_fr() -> Self {
        let mut delays = Vec::with_capacity(33);
        delays.push(0); // text
        delays.push(0); // first audio codebook
        delays.extend(std::iter::repeat_n(2, 31)); // codebooks 2..32

        let mut conditioners: BTreeMap<String, ConditionerConfig> = BTreeMap::new();
        conditioners.insert(
            "speaker_wavs".into(),
            ConditionerKind::Tensor {
                tensor: TensorConditioner { dim: 512 },
            },
        );
        conditioners.insert(
            "cfg".into(),
            ConditionerKind::Lut {
                lut: LutConditioner {
                    n_bins: 7,
                    dim: 16,
                    tokenizer: "noop".into(),
                    possible_values: ["1.0", "1.5", "2.0", "2.5", "3.0", "3.5", "4.0"]
                        .into_iter()
                        .map(String::from)
                        .collect(),
                },
            },
        );
        conditioners.insert(
            "control".into(),
            ConditionerKind::Lut {
                lut: LutConditioner {
                    n_bins: 1,
                    dim: 2048,
                    tokenizer: "noop".into(),
                    possible_values: vec!["ok".into()],
                },
            },
        );

        Self {
            dim: 2048,
            num_heads: 16,
            num_layers: 16,
            hidden_scale: 4.125,
            causal: true,
            context: 500,
            max_period: 10_000,
            gating: "silu".into(),
            norm: "rms_norm_f32".into(),
            positional_embedding: PositionalEmbedding::Rope,

            card: 2048,
            n_q: 32,
            dep_q: 32,
            delays,
            text_card: 8000,
            text_card_out: None,
            existing_text_padding_id: 3,

            depformer: DepFormerConfig {
                dim: 1024,
                num_heads: 16,
                num_layers: 4,
                dim_feedforward: 3072,
                multi_linear: true,
                positional_embedding: PositionalEmbedding::None,
                weights_per_step: true,
                weights_per_step_schedule: DEPFORMER_WEIGHTS_PER_STEP_SCHEDULE.to_vec(),
                low_rank_embeddings: 128,
            },

            demux_second_stream: true,
            cross_attention: true,
            conditioners,
            fuser: FuserConfig {
                cross_attention_pos_emb: true,
                cross_attention_pos_emb_scale: 1.0,
                sum: vec!["control".into(), "cfg".into()],
                prepend: vec![],
                cross: vec!["speaker_wavs".into()],
            },
            tts_config: TtsConfig {
                audio_delay: 1.28,
                second_stream_ahead: 2,
            },
        }
    }

    /// Backbone temporal transformer stack as a [`TransformerConfig`].
    pub fn backbone(&self) -> TransformerConfig {
        TransformerConfig {
            d_model: self.dim,
            num_heads: self.num_heads,
            num_layers: self.num_layers,
            dim_feedforward: (self.dim as f32 * self.hidden_scale).round() as usize,
            causal: self.causal,
            context: self.context,
            max_period: self.max_period,
            positional_embedding: self.positional_embedding,
        }
    }

    /// Frame rate of the Mimi codec (12.5 Hz).
    pub fn frame_rate_hz(&self) -> f32 {
        12.5
    }

    /// Number of frames the audio stream lags text (`audio_delay * 12.5`).
    pub fn audio_delay_frames(&self) -> usize {
        (self.tts_config.audio_delay * self.frame_rate_hz()).round() as usize
    }

    /// Padding token id for the audio stream (`card`).
    pub fn audio_pad_token(&self) -> u32 {
        self.card as u32
    }
}

/// `depformer_weights_per_step_schedule` from the published config (33-entry codebook → head map).
///
/// Indices 0..8 each have their own head; 8..16 share head 8, 16..24 share head 9,
/// 24..32 share head 10. Total: 11 heads for 32 codebooks.
pub const DEPFORMER_WEIGHTS_PER_STEP_SCHEDULE: [usize; 32] = [
    0, 1, 2, 3, 4, 5, 6, 7, // codebooks 0..8: own head
    8, 8, 8, 8, 8, 8, 8, 8, // codebooks 8..16: head 8
    9, 9, 9, 9, 9, 9, 9, 9, // codebooks 16..24: head 9
    10, 10, 10, 10, 10, 10, 10, 10, // codebooks 24..32: head 10
];

/// `delays` from the published config (33 entries: 1 text + 32 audio).
pub const DELAYS_DEFAULT: [i32; 33] = [
    0, 0, // text + first audio codebook
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, // codebooks 1..16
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, // codebooks 17..32
];
