// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! # rlx-vlash
//!
//! Native RLX port of the [VLASH](https://github.com/mit-han-lab/vlash)
//! **π₀** and **π₀.₅** Vision-Language-Action robot policies.
//!
//! Both policies pair a **PaliGemma** backbone (SigLIP-So400m/14 @224 vision
//! tower + a Gemma-2B text model) with a smaller **Gemma-300M action expert**.
//! The two Gemma stacks run through 18 *joint* transformer layers that share a
//! single attention over the concatenated `[image ++ text ++ suffix]`
//! sequence; actions are generated by **flow matching** (a short Euler
//! integration of a learned velocity field).
//!
//! Pipeline (`sample_actions`):
//! 1. **Prefix** — SigLIP patch tokens ++ Gemma token embeddings (scaled by
//!    `√hidden`), attended bidirectionally.
//! 2. **Denoise loop** — for `num_inference_steps` steps, embed the suffix
//!    (state / noisy actions / time), run the 18 joint layers, and read the
//!    velocity `v_t` from `action_out_proj`; integrate `x_t += dt · v_t`.
//!
//! Both variants reproduce the original VLASH implementation on the published
//! `lerobot/pi0_base` / `lerobot/pi05_base` checkpoints at **cosine 1.0** across
//! every stage (vision features → prefix → denoise step → full action chunk);
//! see `scripts/run_parity.py` and `tests/parity.rs`. Runs on CPU, Metal, MLX,
//! wgpu, and Vulkan.
//!
//! Entry points:
//!   - [`VlashRunner`] — load a checkpoint / prepped bundle and
//!     `predict_action_chunk`.
//!   - [`VlashConfig`] / [`VlashVariant`] — model dimensions + policy family.
//!   - [`load_prepped`] — load safetensors / GGUF / rlxp into a `WeightMap`;
//!     [`write_gguf`] / [`write_rlxp`] + [`QuantScheme`] prepare RLX-native
//!     bundles (see the `prep_weights` example).
//!   - [`canonical_key`] — OpenPI→RLX checkpoint key remapping.

pub mod config;
pub mod flow;
pub mod joint_layer;
pub mod normalize;
pub mod prefix;
pub mod prep;
pub mod preprocess;
pub mod runner;
pub mod sample;
pub mod suffix;
pub mod testkit;
pub mod tokenizer;
pub mod util;
pub mod vision;
pub mod weights;

pub use config::{GemmaConfig, VisionConfig, VlashConfig, VlashVariant};
pub use flow::build_denoise_flow;
pub use normalize::{MeanStd, Normalization};
pub use prep::{QuantScheme, load_prepped, read_gguf, read_rlxp, write_gguf, write_rlxp};
pub use preprocess::{resize_with_pad_normalize, rgb8_to_nchw_normalized};
pub use runner::{VlashRunner, VlashRunnerBuilder};
pub use sample::sample_actions;
pub use tokenizer::{PaligemmaTokenizer, TokenizedPrompt};
pub use vision::build_vision_flow;
pub use weights::{canonical_key, load_remapped, remap};
