//! Build a compatibility catalog of huggingface.co/mlx-community checkpoints
//! against the generic standard-decoder builder. Pulls the org's most-downloaded
//! text-generation models, fetches each `config.json`, and classifies it with
//! the AUTHORITATIVE [`rlx_models_core::classify_config`] (same verdict the
//! loader enforces), then writes `docs/mlx-community-support.{md,json}` so the
//! "which mlx-community models does rlx run natively" list is committed & handy.
//!
//! Uses `curl` for HTTP (no HTTP dep in the core crate). Regenerate with:
//!   cargo run --release -p rlx-models-core --example mlx_catalog -- [limit]
//!
//! `limit` = how many top-by-downloads text-gen repos to scan (default 200).

use anyhow::{Result, anyhow};
use rlx_models_core::{CoverageVia, ModelCoverage, classify_coverage};
use std::io::Write;
use std::process::Command;

fn curl(url: &str) -> Option<String> {
    let out = Command::new("curl")
        .args(["-sL", "--max-time", "25", url])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8_lossy(&out.stdout).to_string();
    if s.trim().is_empty() { None } else { Some(s) }
}

struct Row {
    id: String,
    downloads: u64,
    sup: Option<ModelCoverage>, // None = no reachable config.json
}

/// How a covered model runs, for the catalog `via` column.
fn via_str(via: CoverageVia) -> String {
    match via {
        CoverageVia::Generic => "generic".to_string(),
        CoverageVia::Dedicated(k) => k.to_string(),
        CoverageVia::None => "—".to_string(),
    }
}

fn main() -> Result<()> {
    let limit: usize = std::env::args()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or(200);
    let out_dir = std::env::args().nth(2).unwrap_or_else(|| "docs".into());

    let list_url = format!(
        "https://huggingface.co/api/models?author=mlx-community\
         &pipeline_tag=text-generation&sort=downloads&direction=-1&limit={limit}&full=false"
    );
    eprintln!("[catalog] fetching top {limit} text-generation repos …");
    let list = curl(&list_url).ok_or_else(|| anyhow!("HF API model list failed (curl)"))?;
    let models: serde_json::Value = serde_json::from_str(&list)?;
    let arr = models
        .as_array()
        .ok_or_else(|| anyhow!("HF API did not return an array"))?;
    eprintln!("[catalog] {} repos; fetching configs …", arr.len());

    let mut rows: Vec<Row> = Vec::with_capacity(arr.len());
    for (i, m) in arr.iter().enumerate() {
        let Some(id) = m.get("id").and_then(|x| x.as_str()) else {
            continue;
        };
        let downloads = m.get("downloads").and_then(|x| x.as_u64()).unwrap_or(0);
        let cfg_url = format!("https://huggingface.co/{id}/raw/main/config.json");
        let sup = curl(&cfg_url)
            .and_then(|s| serde_json::from_str::<serde_json::Value>(&s).ok())
            .map(|v| classify_coverage(&v));
        if (i + 1) % 25 == 0 {
            eprintln!("[catalog]  {}/{}", i + 1, arr.len());
        }
        rows.push(Row {
            id: id.to_string(),
            downloads,
            sup,
        });
    }

    // Supported first, then by downloads.
    rows.sort_by(|a, b| {
        let sa = a.sup.as_ref().map(|s| s.supported).unwrap_or(false);
        let sb = b.sup.as_ref().map(|s| s.supported).unwrap_or(false);
        sb.cmp(&sa).then(b.downloads.cmp(&a.downloads))
    });

    let n_total = rows.len();
    let n_sup = rows
        .iter()
        .filter(|r| r.sup.as_ref().is_some_and(|s| s.supported))
        .count();

    std::fs::create_dir_all(&out_dir).ok();
    let md_path = format!("{out_dir}/mlx-community-support.md");
    let json_path = format!("{out_dir}/mlx-community-support.json");

    // ── Markdown ──
    let mut md = String::new();
    md.push_str("# mlx-community × rlx generic decoder — support catalog\n\n");
    md.push_str(&format!(
        "Auto-generated by `cargo run -p rlx-models-core --example mlx_catalog`. \
         Classifier: `rlx_models_core::classify_coverage` (authoritative — reports \
         whether rlx runs a checkpoint via ANY path: the generic \
         `build_standard_decoder_packed` OR a dedicated crate).\n\n\
         **{n_sup} / {n_total}** of the top-{limit} most-downloaded text-generation \
         repos are supported. The `via` column is `generic` (no per-model crate) or a \
         crate name; `status` is `validated` (run vs an mlx-lm oracle) or `wired \
         (validation deferred)` for 100B+ MoE too large for local cos-parity.\n\n\
         Run a generic one: `cargo run -p rlx-models-core --example mlx_auto_run -- <dir> <device>`.\n\n"
    ));
    md.push_str(
        "| ✓ | repo | arch | via | status | act | rope | tie | vocab | hidden | layers | note |\n",
    );
    md.push_str(
        "|---|------|------|-----|--------|-----|------|-----|-------|--------|--------|------|\n",
    );
    for r in &rows {
        match &r.sup {
            Some(s) => md.push_str(&format!(
                "| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
                if s.supported { "✅" } else { "—" },
                r.id,
                s.base.arch,
                via_str(s.via),
                s.status.tag(),
                s.base.hidden_act,
                s.base.rope,
                if s.base.tie_word_embeddings { "y" } else { "n" },
                s.base.vocab_size,
                s.base.hidden_size,
                s.base.num_hidden_layers,
                s.reason,
            )),
            None => md.push_str(&format!(
                "| ? | {} | — | — | — | — | — | — | — | — | — | no config.json |\n",
                r.id
            )),
        }
    }
    std::fs::File::create(&md_path)?.write_all(md.as_bytes())?;

    // ── JSON ──
    let json: Vec<serde_json::Value> = rows
        .iter()
        .map(|r| match &r.sup {
            Some(s) => serde_json::json!({
                "repo": r.id, "downloads": r.downloads, "supported": s.supported,
                "via": via_str(s.via), "status": s.status.tag(),
                "arch": s.base.arch, "reason": s.reason, "hidden_act": s.base.hidden_act,
                "rope": s.base.rope, "tie": s.base.tie_word_embeddings, "vocab": s.base.vocab_size,
                "hidden": s.base.hidden_size, "layers": s.base.num_hidden_layers, "experts": s.base.num_experts,
            }),
            None => serde_json::json!({ "repo": r.id, "downloads": r.downloads, "supported": false, "reason": "no config.json" }),
        })
        .collect();
    std::fs::File::create(&json_path)?
        .write_all(serde_json::to_string_pretty(&json)?.as_bytes())?;

    println!("catalog: {n_sup}/{n_total} supported → {md_path} , {json_path}");
    Ok(())
}
