// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
// SPDX-License-Identifier: MIT OR Apache-2.0

`include "tv_defs.svh"

// Sequential inference engine.
//
// Every stage of this network is "bias, then a dot product over some address
// pattern, then requantise and activate", so there is one datapath and a
// descriptor ROM rather than a module per layer. Recurrence needs no special
// handling: the LSTM states live in the activation RAM like any other tensor.
//
// Addresses are generated by running accumulators (`*_row` / `*_col` / `*_tap`)
// instead of multipliers, so the address path costs adders only.
//
// One MAC every two cycles: one to present the addresses, one to accumulate
// the registered reads. That is ~170 k cycles per 16 ms frame, so 62.5 fps
// needs ~11 MHz. Halving it to one MAC per cycle is a mechanical change —
// present tap i+1's address while accumulating tap i.
module tv_core (
    input  logic               clk,
    input  logic               rst_n,
    // Feature load: write `TV_FEAT_N` Q15 words before raising `start`.
    input  logic               feat_we,
    input  logic [11:0]        feat_addr,
    input  logic signed [31:0] feat_data,
    input  logic               start,
    output logic               busy,
    output logic               done,
    output logic signed [31:0] prob
);
  // ---- memories ------------------------------------------------------------
  logic signed [31:0] aram [0:`TV_ARAM-1];
  logic signed [15:0] wram [0:`TV_WRAM-1];
  logic        [15:0] oram [0:`TV_OFFN-1];
  initial begin
    $readmemh("weights.mem", wram);
    $readmemh("offsets.mem", oram);
    // Zero-initialised: LSTM state starts at zero, and the padding guard cells
    // in the conv regions are never written, so they stay zero.
    for (int i = 0; i < `TV_ARAM; i++) aram[i] = '0;
  end

  // ---- descriptor ROM ------------------------------------------------------
  logic [4:0] pc;
  logic [`TV_FIELD_W-1:0]
      op, act, n_o, n_i, n_tap,
      base_a, sa_o, sa_i, sa_t, off_ptr, use_off,
      base_w, sw_o, sw_i, sw_t,
      base_b, sb_o, sb_i, has_bias, b_shift,
      w_frac, base_d, sd_o, sd_i, base_c;
  always_comb begin
    `include "tv_ucode.svh"
  end

  // ---- loop state ----------------------------------------------------------
  logic [19:0] oo, ii, ti;
  logic [19:0] a_row, a_col, a_tap, w_row, w_col, w_tap, b_row, b_col, d_row, d_col;
  logic signed [`TV_ACC_W-1:0] acc;
  logic signed [31:0] res;

  // ---- memory ports --------------------------------------------------------
  logic [11:0] a_addr;
  logic [19:0] w_addr;
  logic               a_we;
  logic [11:0]        a_waddr;
  logic signed [31:0] a_wdata;
  logic signed [31:0] a_q;
  logic signed [15:0] w_q;

  always_ff @(posedge clk) begin
    if (feat_we)     aram[feat_addr] <= feat_data;
    else if (a_we)   aram[a_waddr]   <= a_wdata;
    a_q <= aram[a_addr];
    w_q <= wram[w_addr[16:0]];
  end

  // ---- activation LUT ------------------------------------------------------
  logic               lut_sel;
  logic signed [31:0] lut_x, lut_y;
  tv_lut u_lut (.clk(clk), .sel(lut_sel), .x(lut_x), .y(lut_y));

  // ---- gate registers ------------------------------------------------------
  logic signed [31:0] zi, zf, zg, zo, cc, ig, fg, gg, og, nc;

  typedef enum logic [4:0] {
    S_IDLE, S_FETCH, S_OUT, S_BIAS, S_BIAS_W, S_TAP, S_TAP_W,
    S_REQ, S_ACT_P, S_ACT_W, S_WRITE, S_NEXT, S_RD_PROB, S_RD_PROB_W,
    S_G_RD0, S_G_RD1, S_G_RD2, S_G_RD3, S_G_RD4, S_G_RD5,
    S_G_L0, S_G_L1, S_G_L2, S_G_L3, S_G_L4, S_G_L5, S_G_WC, S_G_WH, S_G_NEXT
  } state_t;
  state_t st;

  // Round-to-nearest arithmetic shift; truncation would bias every stage by
  // half an LSB and the LSTM feeds its own output back.
  function automatic logic signed [31:0] rsh(
      input logic signed [`TV_ACC_W-1:0] v, input logic [`TV_FIELD_W-1:0] s);
    logic signed [`TV_ACC_W-1:0] t;
    begin
      t = (s == 0) ? v : ((v + (1 << (s - 1))) >>> s);
      rsh = t[31:0];
    end
  endfunction

  // The LUT input is selected by state so a lookup costs one cycle: present in
  // state N, capture in state N+1 while presenting the next.
  always_comb begin
    lut_sel = 1'b0;
    lut_x   = res;
    case (st)
      S_G_L0: begin lut_sel = 1'b0; lut_x = zi; end
      S_G_L1: begin lut_sel = 1'b0; lut_x = zf; end
      S_G_L2: begin lut_sel = 1'b1; lut_x = zg; end
      S_G_L3: begin lut_sel = 1'b0; lut_x = zo; end
      S_G_L5: begin lut_sel = 1'b1; lut_x = nc; end
      default: ;
    endcase
  end

  always_comb begin
    a_addr = 12'(a_col);
    w_addr = w_col;
    case (st)
      // Offset-table taps (the conv windows) read a tiny ROM; strided taps walk
      // an accumulator. Either way the address path has no multiplier.
      S_TAP, S_TAP_W: begin
        a_addr = 12'(use_off != 0 ? a_col + 20'(oram[off_ptr + ti]) : a_tap);
        w_addr = w_tap;
      end
      S_BIAS, S_BIAS_W: w_addr = b_col;
      S_G_RD0: a_addr = 12'(base_a + oo);
      S_G_RD1: a_addr = 12'(base_a + `TV_HIDDEN + oo);
      S_G_RD2: a_addr = 12'(base_a + 2 * `TV_HIDDEN + oo);
      S_G_RD3: a_addr = 12'(base_a + 3 * `TV_HIDDEN + oo);
      S_G_RD4: a_addr = 12'(base_c + oo);
      S_RD_PROB, S_RD_PROB_W: a_addr = `TV_PROB_ADDR;
      default: ;
    endcase
  end

  assign busy = (st != S_IDLE);

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      st   <= S_IDLE;
      pc   <= '0;
      done <= 1'b0;
      prob <= '0;
      a_we <= 1'b0;
    end else begin
      a_we <= 1'b0;
      case (st)
        S_IDLE: if (start) begin
          pc <= '0; done <= 1'b0; st <= S_FETCH;
        end

        // Reset the per-descriptor loop bases.
        S_FETCH: begin
          oo <= '0; ii <= '0;
          a_row <= 20'(base_a); a_col <= 20'(base_a);
          w_row <= 20'(base_w); w_col <= 20'(base_w);
          b_row <= 20'(base_b); b_col <= 20'(base_b);
          d_row <= 20'(base_d); d_col <= 20'(base_d);
          case (op)
            `TV_OP_DONE: st <= S_RD_PROB;
            `TV_OP_GATE: st <= S_G_RD0;
            default:     st <= S_OUT;
          endcase
        end

        S_OUT: begin
          ti    <= '0;
          acc   <= '0;
          a_tap <= a_col;
          w_tap <= w_col;
          if (op == `TV_OP_POOL) begin
            // Pool seeds from the first tap rather than zero: activations are
            // post-ReLU here, but seeding at zero would still be wrong for a
            // max over negatives.
            st <= S_TAP;
          end else if (has_bias != 0) begin
            st <= S_BIAS;
          end else begin
            st <= S_TAP;
          end
        end

        S_BIAS:   st <= S_BIAS_W;
        S_BIAS_W: begin
          acc <= `TV_ACC_W'($signed(w_q)) <<< b_shift;
          st  <= S_TAP;
        end

        S_TAP:   st <= S_TAP_W;
        S_TAP_W: begin
          if (op == `TV_OP_POOL)
            acc <= (ti == 0 || $signed(a_q) > $signed(acc[31:0]))
                     ? `TV_ACC_W'($signed(a_q)) : acc;
          else
            acc <= acc + `TV_ACC_W'($signed(a_q) * $signed(w_q));
          if (ti + 1 == n_tap) st <= S_REQ;
          else begin
            ti    <= ti + 1;
            a_tap <= a_tap + sa_t;
            w_tap <= w_tap + sw_t;
            st    <= S_TAP;
          end
        end

        S_REQ: begin
          res <= (op == `TV_OP_POOL) ? $signed(acc[31:0]) : rsh(acc, w_frac);
          if (act == `TV_ACT_SIG) st <= S_ACT_P;
          else                    st <= S_WRITE;
        end

        // `res` sits on `lut_x`; the ROM answers on the next edge.
        S_ACT_P: st <= S_ACT_W;
        S_ACT_W: begin res <= lut_y; st <= S_WRITE; end

        S_WRITE: begin
          a_we    <= 1'b1;
          a_waddr <= 12'(d_col);
          a_wdata <= (act == `TV_ACT_RELU && $signed(res) < 0) ? 32'sd0 : res;
          st      <= S_NEXT;
        end

        S_NEXT: begin
          if (ii + 1 < n_i) begin
            ii    <= ii + 1;
            a_col <= a_col + sa_i;
            w_col <= w_col + sw_i;
            b_col <= b_col + sb_i;
            d_col <= d_col + sd_i;
            st    <= S_OUT;
          end else if (oo + 1 < n_o) begin
            oo    <= oo + 1;
            ii    <= '0;
            a_row <= a_row + sa_o; a_col <= a_row + sa_o;
            w_row <= w_row + sw_o; w_col <= w_row + sw_o;
            b_row <= b_row + sb_o; b_col <= b_row + sb_o;
            d_row <= d_row + sd_o; d_col <= d_row + sd_o;
            st    <= S_OUT;
          end else begin
            pc <= pc + 1; st <= S_FETCH;
          end
        end

        // ---- LSTM gating: c = f*c + i*g, h = o*tanh(c) --------------------
        S_G_RD0: st <= S_G_RD1;
        S_G_RD1: begin zi <= a_q; st <= S_G_RD2; end
        S_G_RD2: begin zf <= a_q; st <= S_G_RD3; end
        S_G_RD3: begin zg <= a_q; st <= S_G_RD4; end
        S_G_RD4: begin zo <= a_q; st <= S_G_RD5; end
        S_G_RD5: begin cc <= a_q; st <= S_G_L0; end
        S_G_L0:  st <= S_G_L1;
        S_G_L1:  begin ig <= lut_y; st <= S_G_L2; end
        S_G_L2:  begin fg <= lut_y; st <= S_G_L3; end
        S_G_L3:  begin gg <= lut_y; st <= S_G_L4; end
        S_G_L4:  begin
          og <= lut_y;
          nc <= rsh(`TV_ACC_W'($signed(fg) * $signed(cc))
                  + `TV_ACC_W'($signed(ig) * $signed(gg)), `TV_ACT_FRAC);
          st <= S_G_L5;
        end
        S_G_L5:  st <= S_G_WC;
        S_G_WC: begin
          a_we    <= 1'b1;
          a_waddr <= 12'(base_c + oo);
          a_wdata <= nc;
          res     <= rsh(`TV_ACC_W'($signed(og) * $signed(lut_y)), `TV_ACT_FRAC);
          st      <= S_G_WH;
        end
        S_G_WH: begin
          a_we    <= 1'b1;
          a_waddr <= 12'(base_d + oo);
          a_wdata <= res;
          st      <= S_G_NEXT;
        end
        S_G_NEXT: begin
          if (oo + 1 < n_i) begin oo <= oo + 1; st <= S_G_RD0; end
          else begin pc <= pc + 1; st <= S_FETCH; end
        end

        S_RD_PROB:   st <= S_RD_PROB_W;
        S_RD_PROB_W: begin
          prob <= a_q;
          done <= 1'b1;
          st   <= S_IDLE;
        end
        default: st <= S_IDLE;
      endcase
    end
  end
endmodule
