// @generated by rlx-fpga (seq target) -- do not edit by hand.
`ifndef TV_DEFS_SVH
`define TV_DEFS_SVH

`define TV_ARAM      2048      // activation words
`define TV_WRAM      74986      // int16 weights
`define TV_OFFN      9
`define TV_UCODE_N   14
`define TV_ACT_FRAC  15
`define TV_LUT_N     1024
`define TV_LUT_SHIFT 9
`define TV_FEAT_BASE 0
`define TV_FEAT_N    123
`define TV_PROB_ADDR 971
`define TV_HIDDEN    64
`define TV_ACC_W     48
`define TV_FIELD_W   17

`define TV_OP_MATVEC 0
`define TV_OP_POOL   1
`define TV_OP_GATE   2
`define TV_OP_DONE   3
`define TV_ACT_NONE  0
`define TV_ACT_RELU  1
`define TV_ACT_SIG   2

`endif
