// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
// SPDX-License-Identifier: GPL-3.0-only
//
// @generated by scripts/gen_ten_vad_layout.py — do not edit by hand.

//! Where each tensor sits inside `weights/ten_vad.safetensors`, resolved at
//! build time.
//!
//! The safetensors header is JSON. Parsing JSON on an MCU just to find a tensor
//! costs flash and a dependency, and the file is committed and fixed — so its
//! layout is a constant. `weights::layout_matches_blob` re-derives this from the
//! blob at test time and fails if the two ever drift.

/// `(name, f32-element offset into the blob, element count)`.
pub const LAYOUT: [(&str, usize, usize); 22] = [
    ("conv0.bias", 434, 16),               // [16]
    ("conv0.depthwise.weight", 450, 9),    // [1, 1, 3, 3]
    ("conv0.pointwise.weight", 459, 16),   // [16, 1, 1, 1]
    ("dense1.bias", 475, 32),              // [32]
    ("dense1.weight", 507, 4096),          // [128, 32]
    ("dense2.bias", 4603, 1),              // [1]
    ("dense2.weight", 4604, 32),           // [32, 1]
    ("feature.mean", 4636, 41),            // [41]
    ("feature.std", 4677, 41),             // [41]
    ("lstm1.bias", 4718, 256),             // [256]
    ("lstm1.weight_hh", 4974, 16384),      // [256, 64]
    ("lstm1.weight_ih", 21358, 20480),     // [256, 80]
    ("lstm2.bias", 41838, 256),            // [256]
    ("lstm2.weight_hh", 42094, 16384),     // [256, 64]
    ("lstm2.weight_ih", 58478, 16384),     // [256, 64]
    ("sep1.bias", 74862, 16),              // [16]
    ("sep1.depthwise.weight", 74878, 48),  // [16, 1, 3, 1]
    ("sep1.pointwise.weight", 74926, 256), // [16, 16, 1, 1]
    ("sep2.bias", 75182, 16),              // [16]
    ("sep2.depthwise.weight", 75198, 48),  // [16, 1, 3, 1]
    ("sep2.pointwise.weight", 75246, 256), // [16, 16, 1, 1]
    ("stft.window", 75502, 768),           // [768]
];
