// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
// SPDX-License-Identifier: GPL-3.0-only

//! Generate the integer-only artifacts for `rlx-ten-vad-core`.
//!
//! Writes `weights/ten_vad_q15.bin` and `src/fixed_tables.rs`. Run after
//! changing the weights or the numeric format:
//!
//! ```text
//! cargo run -p rlx-ten-vad --release --example gen_fixed_tables
//! ```
//!
//! The quantiser is `rlx_fpga::seq::quantise_pow2` — the same function the RTL
//! exporter uses — so the MCU blob and the FPGA weight image are identical
//! integers by construction rather than by two implementations agreeing.

use rlx_fpga::seq::quantise_pow2;
use rlx_ten_vad_core::weights::blob_f32;
use rlx_ten_vad_core::weights_layout::LAYOUT;
use std::fmt::Write as _;
use std::path::Path;

/// Execution order of the datapath, and the order tensors sit in the blob.
const NET_ORDER: [&str; 19] = [
    "conv0.depthwise.weight",
    "conv0.pointwise.weight",
    "conv0.bias",
    "sep1.depthwise.weight",
    "sep1.pointwise.weight",
    "sep1.bias",
    "sep2.depthwise.weight",
    "sep2.pointwise.weight",
    "sep2.bias",
    "lstm1.weight_ih",
    "lstm1.weight_hh",
    "lstm1.bias",
    "lstm2.weight_ih",
    "lstm2.weight_hh",
    "lstm2.bias",
    "dense1.weight",
    "dense1.bias",
    "dense2.weight",
    "dense2.bias",
];

const ACT_FRAC: u32 = 15;
const LUT_N: usize = 1024;
const LUT_HI: f64 = 16.0;

fn tensor(name: &str) -> &'static [f32] {
    let (_, off, len, ..) = LAYOUT
        .iter()
        .find(|(n, ..)| *n == name)
        .map(|&(n, o, l)| (n, o, l, ()))
        .unwrap_or_else(|| panic!("no tensor named {name}"));
    &blob_f32()[off..off + len]
}

fn main() -> anyhow::Result<()> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../rlx-ten-vad-core");

    let mut frac: Vec<u32> = Vec::with_capacity(NET_ORDER.len());
    let mut quant: Vec<Vec<i16>> = Vec::with_capacity(NET_ORDER.len());
    for name in NET_ORDER {
        let (q, f) = quantise_pow2(tensor(name));
        quant.push(q);
        frac.push(f);
    }
    // Each LSTM's two projections land in one accumulator, so they must share a
    // scale — otherwise the datapath needs a second accumulator and a rescale
    // purely to keep one extra bit on W_hh.
    for pair in [
        ("lstm1.weight_ih", "lstm1.weight_hh"),
        ("lstm2.weight_ih", "lstm2.weight_hh"),
    ] {
        let ia = NET_ORDER.iter().position(|n| *n == pair.0).unwrap();
        let ib = NET_ORDER.iter().position(|n| *n == pair.1).unwrap();
        let shared = frac[ia].min(frac[ib]);
        for &i in &[ia, ib] {
            if frac[i] != shared {
                let scale = f64::from(1u32 << shared);
                quant[i] = tensor(NET_ORDER[i])
                    .iter()
                    .map(|&x| (f64::from(x) * scale).round().clamp(-32768.0, 32767.0) as i16)
                    .collect();
                frac[i] = shared;
            }
        }
    }

    let mut blob: Vec<u8> = Vec::new();
    let mut layout: Vec<(&str, usize, usize, u32)> = Vec::new();
    for (i, name) in NET_ORDER.iter().enumerate() {
        layout.push((name, blob.len() / 2, quant[i].len(), frac[i]));
        for &v in &quant[i] {
            blob.extend_from_slice(&v.to_le_bytes());
        }
    }
    std::fs::create_dir_all(root.join("weights"))?;
    std::fs::write(root.join("weights/ten_vad_q15.bin"), &blob)?;

    let lut = |f: fn(f64) -> f64| -> Vec<i16> {
        (0..=LUT_N)
            .map(|i| {
                let x = LUT_HI * i as f64 / LUT_N as f64;
                (f(x) * 32768.0).round().min(32767.0) as i16
            })
            .collect()
    };
    let sigmoid = lut(|x| 1.0 / (1.0 + (-x).exp()));
    let tanh = lut(f64::tanh);

    let mut out = String::new();
    writeln!(out, "// RLX — versatile ML compiler + runtime.")?;
    writeln!(
        out,
        "// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna."
    )?;
    writeln!(out, "// SPDX-License-Identifier: GPL-3.0-only")?;
    writeln!(out, "//")?;
    writeln!(
        out,
        "// @generated by `cargo run -p rlx-ten-vad --example gen_fixed_tables`."
    )?;
    writeln!(out, "// Do not edit by hand.\n")?;
    writeln!(
        out,
        "//! Constants for the integer-only datapath in [`crate::fixed`]."
    )?;
    writeln!(out, "//!")?;
    writeln!(
        out,
        "//! Weights are int16 with a per-tensor power-of-two scale; activations are"
    )?;
    writeln!(
        out,
        "//! Q{ACT_FRAC}. The LUTs hold {} points of sigmoid and tanh over [0, {LUT_HI}] in",
        LUT_N + 1
    )?;
    writeln!(
        out,
        "//! Q15, linearly interpolated. That range is not cosmetic: clamping at 8"
    )?;
    writeln!(
        out,
        "//! instead of 16 costs 6.9e-3, because LSTM pre-activations reach 177.\n"
    )?;
    writeln!(out, "/// Fractional bits in an activation.")?;
    writeln!(out, "pub const ACT_FRAC: u32 = {ACT_FRAC};")?;
    writeln!(
        out,
        "/// LUT interval count; the domain is split so the index is a pure shift."
    )?;
    writeln!(out, "pub const LUT_N: usize = {LUT_N};")?;
    writeln!(
        out,
        "/// The shift that turns a Q{ACT_FRAC} value into a LUT index."
    )?;
    let shift = ((1u64 << ACT_FRAC) as f64 * LUT_HI / LUT_N as f64)
        .log2()
        .round() as u32;
    writeln!(out, "pub const LUT_SHIFT: u32 = {shift};\n")?;
    writeln!(
        out,
        "/// `(name, int16-element offset, count, weight fractional bits)`."
    )?;
    writeln!(
        out,
        "pub const LAYOUT: [(&str, usize, usize, u32); {}] = [",
        layout.len()
    )?;
    for (n, o, c, f) in &layout {
        writeln!(out, "    (\"{n}\", {o}, {c}, {f}),")?;
    }
    writeln!(out, "];\n")?;
    writeln!(
        out,
        "// Per-tensor `(int16 offset, count, fractional bits)`, so the datapath"
    )?;
    writeln!(out, "// indexes the blob without a name lookup.")?;
    for (n, o, c, f) in &layout {
        writeln!(out, "/// `{n}` — {c} elements, Q{f}.")?;
        writeln!(
            out,
            "pub const {}: (usize, usize, u32) = ({o}, {c}, {f});",
            n.replace('.', "_").to_uppercase()
        )?;
    }
    writeln!(out, "\n/// Total int16 elements in the blob.")?;
    writeln!(out, "pub const BLOB_LEN: usize = {};\n", blob.len() / 2)?;
    for (name, doc, tab) in [
        ("SIGMOID_Q15", "sigmoid", &sigmoid),
        ("TANH_Q15", "tanh", &tanh),
    ] {
        writeln!(out, "/// {doc} over [0, {LUT_HI}] in Q15.")?;
        writeln!(out, "pub static {name}: [i16; {}] = [", tab.len())?;
        for row in tab.chunks(12) {
            writeln!(
                out,
                "    {}",
                row.iter()
                    .map(|v| format!("{v},"))
                    .collect::<Vec<_>>()
                    .join(" ")
            )?;
        }
        writeln!(out, "];\n")?;
    }
    std::fs::write(root.join("src/fixed_tables.rs"), out)?;

    let total: usize = layout.iter().map(|&(_, _, c, _)| c).sum();
    println!(
        "weights {total} params -> {} B ({:.1} kB int16)",
        blob.len(),
        blob.len() as f64 / 1024.0
    );
    println!("luts    2 x {} x i16 over [0, {LUT_HI}]", LUT_N + 1);
    println!("wrote   weights/ten_vad_q15.bin, src/fixed_tables.rs");
    Ok(())
}
