//! Markdown matrix tables (model × device) for docs / release notes.

use std::collections::{BTreeMap, BTreeSet};
use std::fs::File;
use std::io::Write;
use std::path::Path;

use anyhow::{Context, Result};

use super::json::BenchRow;

/// Prefer `short`/`plain` rows; fall back to any ok row for the cell.
fn cell_rows<'a>(rows: &'a [BenchRow]) -> BTreeMap<(String, String), &'a BenchRow> {
    let mut best: BTreeMap<(String, String), &BenchRow> = BTreeMap::new();
    for r in rows {
        if r.status != "ok" {
            continue;
        }
        let key = (r.model.clone(), r.device.clone());
        let prefer = r.phrase == "short" && r.scenario == "plain";
        match best.get(&key) {
            None => {
                best.insert(key, r);
            }
            Some(cur) => {
                let cur_prefer = cur.phrase == "short" && cur.scenario == "plain";
                if prefer && !cur_prefer {
                    best.insert(key, r);
                }
            }
        }
    }
    best
}

fn fmt_rtf(v: Option<f64>) -> String {
    match v {
        Some(x) => format!("{x:.2}×"),
        None => "—".into(),
    }
}

fn fmt_cos(v: Option<f64>) -> String {
    match v {
        Some(x) if x.is_finite() => format!("{x:.5}"),
        _ => "—".into(),
    }
}

fn fmt_cov(v: Option<f64>) -> String {
    match v {
        Some(x) if x.is_finite() => format!("{x:.2}"),
        _ => "—".into(),
    }
}

fn fmt_ms(v: Option<f64>) -> String {
    match v {
        Some(x) => format!("{x:.0}"),
        None => "—".into(),
    }
}

fn write_metric_table(
    out: &mut String,
    title: &str,
    models: &BTreeSet<String>,
    devices: &[String],
    cells: &BTreeMap<(String, String), &BenchRow>,
    pick: impl Fn(&BenchRow) -> String,
) {
    out.push_str(&format!("### {title}\n\n"));
    out.push_str("| model |");
    for d in devices {
        out.push_str(&format!(" {d} |"));
    }
    out.push('\n');
    out.push_str("|---|");
    for _ in devices {
        out.push_str("---|");
    }
    out.push('\n');
    for m in models {
        out.push_str(&format!("| {m} |"));
        for d in devices {
            let cell = cells
                .get(&(m.clone(), d.clone()))
                .map(|r| pick(r))
                .unwrap_or_else(|| "—".into());
            out.push_str(&format!(" {cell} |"));
        }
        out.push('\n');
    }
    out.push('\n');
}

/// Write `BACKENDS.md` (or custom path) with RTF / cosine / Whisper / wall-ms matrices.
pub fn write_markdown(path: &Path, rows: &[BenchRow], host_note: &str) -> Result<()> {
    let cells = cell_rows(rows);
    let mut models = BTreeSet::new();
    let mut devices = BTreeSet::new();
    for ((m, d), _) in &cells {
        models.insert(m.clone());
        devices.insert(d.clone());
    }
    // Stable device column order when present.
    let preferred = ["cpu", "metal", "mlx", "gpu", "ane", "cuda", "vulkan"];
    let mut device_cols: Vec<String> = preferred
        .iter()
        .filter(|d| devices.contains(**d))
        .map(|s| (*s).to_string())
        .collect();
    for d in &devices {
        if !device_cols.iter().any(|x| x == d) {
            device_cols.push(d.clone());
        }
    }

    let n_ok = rows.iter().filter(|r| r.status == "ok").count();
    let n_fail = rows.iter().filter(|r| r.status == "failed").count();
    let n_skip = rows.iter().filter(|r| r.status == "skipped").count();

    let mut md = String::new();
    md.push_str("# TTS bench — cross-backend matrix\n\n");
    md.push_str(host_note);
    md.push('\n');
    md.push_str(&format!(
        "Generated by `rlx-tts-bench`. Rows prefer `short`/`plain`. \
         ok={n_ok} failed={n_fail} skipped={n_skip} (all scenarios/phrases in `results.jsonl`).\n\n"
    ));

    write_metric_table(
        &mut md,
        "Realtime factor (higher = faster)",
        &models,
        &device_cols,
        &cells,
        |r| fmt_rtf(r.rtf),
    );
    write_metric_table(
        &mut md,
        "Wall time (ms)",
        &models,
        &device_cols,
        &cells,
        |r| fmt_ms(r.wall_ms),
    );
    write_metric_table(
        &mut md,
        "Cosine vs CPU waveform",
        &models,
        &device_cols,
        &cells,
        |r| fmt_cos(r.cosine_vs_cpu),
    );
    write_metric_table(
        &mut md,
        "Whisper word coverage",
        &models,
        &device_cols,
        &cells,
        |r| fmt_cov(r.whisper.as_ref().map(|w| w.coverage)),
    );

    // Failures / skips for transparency.
    let mut notes = Vec::new();
    for r in rows {
        if r.status == "failed" {
            notes.push(format!(
                "- **{}** / {} / {} / {}: {}",
                r.model,
                r.device,
                r.phrase,
                r.scenario,
                r.error.as_deref().unwrap_or("failed")
            ));
        } else if r.status == "skipped" {
            notes.push(format!(
                "- *{}* / {} / {} / {}: {}",
                r.model,
                r.device,
                r.phrase,
                r.scenario,
                r.skip_reason.as_deref().unwrap_or("skipped")
            ));
        }
    }
    if !notes.is_empty() {
        md.push_str("### Failures / skips\n\n");
        // De-dupe while keeping order.
        let mut seen = BTreeSet::new();
        for n in notes {
            if seen.insert(n.clone()) {
                md.push_str(&n);
                md.push('\n');
            }
        }
        md.push('\n');
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let mut f = File::create(path).with_context(|| format!("{}", path.display()))?;
    f.write_all(md.as_bytes())?;
    Ok(())
}
