// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

use std::path::{Path, PathBuf};

use anyhow::Result;
use rlx_onnx_import::BundleNode;

use crate::plan::{DecomposeOptions, DecomposePlan, WeightsFormat, resolve_rlx_root};

/// Path for `Cargo.toml` `path = "..."` deps from `base` to `target`.
pub fn relativize_path(base: &Path, target: &Path) -> PathBuf {
    let base = base.canonicalize().unwrap_or_else(|_| base.to_path_buf());
    let target = target
        .canonicalize()
        .unwrap_or_else(|_| target.to_path_buf());
    let base_dir = if base.is_dir() {
        base
    } else {
        base.parent().unwrap_or(&base).to_path_buf()
    };
    let mut base_it = base_dir.components().peekable();
    let mut target_it = target.components().peekable();
    while base_it.peek() == target_it.peek() {
        if base_it.peek().is_none() {
            break;
        }
        base_it.next();
        target_it.next();
    }
    let ups = base_it.count();
    let mut rel = PathBuf::new();
    for _ in 0..ups {
        rel.push("..");
    }
    for c in target_it {
        rel.push(c);
    }
    if rel.as_os_str().is_empty() {
        rel.push(".");
    }
    rel
}

pub struct Emitter {
    lines: Vec<String>,
    indent: usize,
}

impl Emitter {
    pub fn new() -> Self {
        Self {
            lines: Vec::new(),
            indent: 0,
        }
    }

    pub fn line(&mut self, s: impl AsRef<str>) {
        let pad = "    ".repeat(self.indent);
        let mut line = String::with_capacity(pad.len() + s.as_ref().len());
        line.push_str(&pad);
        line.push_str(s.as_ref());
        self.lines.push(line);
    }

    pub fn block<F: FnOnce(&mut Self)>(&mut self, f: F) {
        self.indent += 1;
        f(self);
        self.indent -= 1;
    }

    pub fn into_string(self) -> String {
        self.lines.join("\n")
    }
}

pub fn write_generated_crate(
    out_dir: &Path,
    plan: &DecomposePlan,
    weights: WeightsFormat,
    opts: &DecomposeOptions,
) -> Result<()> {
    let src = out_dir.join("src");
    std::fs::create_dir_all(&src)?;
    std::fs::write(
        out_dir.join("Cargo.toml"),
        emit_cargo_toml(out_dir, plan, opts),
    )?;
    std::fs::write(src.join("lib.rs"), emit_lib_rs(plan, weights))?;
    std::fs::write(src.join("graph.rs"), emit_graph_rs(plan))?;
    std::fs::write(src.join("weights.rs"), emit_weights_rs(plan, weights))?;
    let report = serde_json::json!({
        "source_onnx": plan.source_onnx.to_string_lossy(),
        "crate_name": plan.crate_name,
        "lowered": plan.import_report.lowered,
        "skipped": plan.import_report.skipped,
        "unsupported": plan.import_report.unsupported,
        "node_count": plan.manifest.node_count,
        "initializer_count": plan.manifest.initializer_count,
        "op_histogram": plan.manifest.op_histogram,
    });
    std::fs::write(
        out_dir.join("decompose_report.json"),
        serde_json::to_string_pretty(&report)?,
    )?;
    std::fs::write(out_dir.join("README.md"), emit_readme(plan, weights))?;
    Ok(())
}

fn emit_cargo_toml(out_dir: &Path, plan: &DecomposePlan, opts: &DecomposeOptions) -> String {
    let rlx_root = resolve_rlx_root(opts);
    let rlx_ir = relativize_path(out_dir, &rlx_root.join("rlx-ir"));
    let rlx_rt = relativize_path(out_dir, &rlx_root.join("rlx-runtime"));
    format!(
        r#"# Generated by rlx-onnx-decompose — path deps resolved from output directory.

[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
publish = false
description = "RLX native model decomposed from ONNX (auto-generated)"

[dependencies]
anyhow = "1"
rlx-ir = {{ path = "{rlx_ir}" }}
rlx-runtime = {{ path = "{rlx_rt}", default-features = false, features = ["cpu"] }}
safetensors = "0.7"
half = "2"
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"

[features]
default = ["cpu"]
cpu = ["rlx-runtime/cpu"]
cuda = ["rlx-runtime/cuda"]
metal = ["rlx-runtime/metal"]
"#,
        name = plan.crate_name,
        rlx_ir = rlx_ir.display(),
        rlx_rt = rlx_rt.display(),
    )
}

fn emit_lib_rs(plan: &DecomposePlan, weights: WeightsFormat) -> String {
    let weights_mod = match weights {
        WeightsFormat::Safetensors => "safetensors",
        WeightsFormat::Gguf => "gguf",
    };
    format!(
        r#"//! Native RLX model generated from `{}`.
//!
//! Auto-generated by `rlx-onnx-decompose` — do not edit `graph.rs` by hand.

pub mod graph;
pub mod weights;

pub use graph::{{GraphOptions, build_hir}};
pub use weights::load_weights;

/// Compile the decomposed graph on `device` with default RLX options.
pub fn compile(
    device: rlx_runtime::Device,
    weights_path: &std::path::Path,
    opts: &GraphOptions,
) -> anyhow::Result<rlx_runtime::CompiledGraph> {{
    let weights = load_weights(weights_path)?;
    let (hir, params) = build_hir(&weights, opts)?;
    let mut compiled = rlx_runtime::Session::new(device)
        .compile_hir_with(hir, &rlx_runtime::CompileOptions::default())
        .map_err(|e| anyhow::anyhow!("{{0}}", e))?;
    for (name, data) in params {{
        compiled.set_param(name.as_str(), &data);
    }}
    Ok(compiled)
}}

pub const WEIGHTS_FORMAT: &str = "{1}";
"#,
        plan.source_onnx.display(),
        weights_mod,
    )
}

fn emit_weights_rs(plan: &DecomposePlan, _format: WeightsFormat) -> String {
    let mut all_names: Vec<_> = plan.params.keys().chain(plan.i64_params.keys()).collect();
    all_names.sort();
    all_names.dedup();
    format!(
        r#"use std::collections::HashMap;
use std::path::Path;

/// Loaded initializer tensors from `model.safetensors`.
pub struct LoadedWeights {{
    pub f32: HashMap<String, (Vec<f32>, Vec<usize>)>,
    pub i64: HashMap<String, (Vec<i64>, Vec<usize>)>,
}}

fn scale_for<'a>(f32: &'a HashMap<String, (Vec<f32>, Vec<usize>)>, name: &str) -> Option<&'a f32> {{
    f32.get(&format!("{{name}}_scale"))
        .or_else(|| {{
            name.strip_suffix("_quantized")
                .and_then(|base| f32.get(&format!("{{base}}_scale")))
        }})
        .and_then(|(v, _)| v.first())
}}

fn zp_for(f32: &HashMap<String, (Vec<f32>, Vec<usize>)>, name: &str) -> f32 {{
    f32.get(&format!("{{name}}_zero_point"))
        .or_else(|| {{
            name.strip_suffix("_quantized")
                .and_then(|base| f32.get(&format!("{{base}}_zero_point")))
        }})
        .and_then(|(v, _)| v.first().copied())
        .unwrap_or(0.0)
}}

/// Load decomposed weights from `dir` (`model.safetensors`).
pub fn load_weights(dir: &Path) -> anyhow::Result<LoadedWeights> {{
    let path = dir.join("model.safetensors");
    let bytes = std::fs::read(&path)?;
    let st = safetensors::SafeTensors::deserialize(&bytes)?;
    let mut f32 = HashMap::new();
    let mut i64 = HashMap::new();
    let mut pending_quant: Vec<(String, Vec<usize>, Vec<u8>, safetensors::tensor::Dtype)> =
        Vec::new();
    for name in st.names() {{
        let view = st.tensor(name)?;
        let shape: Vec<usize> = view.shape().iter().copied().collect();
        match view.dtype() {{
            safetensors::tensor::Dtype::F32 => {{
                let mut data = Vec::with_capacity(view.data().len() / 4);
                for chunk in view.data().chunks_exact(4) {{
                    data.push(f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]));
                }}
                f32.insert(name.to_string(), (data, shape));
            }}
            safetensors::tensor::Dtype::I64 => {{
                let mut data = Vec::with_capacity(view.data().len() / 8);
                for chunk in view.data().chunks_exact(8) {{
                    data.push(i64::from_le_bytes(chunk.try_into().unwrap()));
                }}
                i64.insert(name.to_string(), (data, shape));
            }}
            safetensors::tensor::Dtype::F16 => {{
                let data: Vec<f32> = view
                    .data()
                    .chunks_exact(2)
                    .map(|c| half::f16::from_le_bytes([c[0], c[1]]).to_f32())
                    .collect();
                f32.insert(name.to_string(), (data, shape));
            }}
            safetensors::tensor::Dtype::BF16 => {{
                let data: Vec<f32> = view
                    .data()
                    .chunks_exact(2)
                    .map(|c| {{
                        let bits = u16::from_le_bytes([c[0], c[1]]);
                        f32::from_bits((bits as u32) << 16)
                    }})
                    .collect();
                f32.insert(name.to_string(), (data, shape));
            }}
            safetensors::tensor::Dtype::U8 | safetensors::tensor::Dtype::I8 => {{
                pending_quant.push((name.to_string(), shape, view.data().to_vec(), view.dtype()));
            }}
            _ => {{}}
        }}
    }}
    for (name, shape, raw, dt) in pending_quant {{
        let scale = scale_for(&f32, &name).copied().unwrap_or(1.0);
        let zp = zp_for(&f32, &name);
        let data: Vec<f32> = match dt {{
            safetensors::tensor::Dtype::U8 => raw.iter().map(|&b| (b as f32 - zp) * scale).collect(),
            _ => raw.iter().map(|&b| (b as i8 as f32 - zp) * scale).collect(),
        }};
        let out_name = name.strip_suffix("_quantized").unwrap_or(&name).to_string();
        if !f32.contains_key(&out_name) {{
            f32.insert(out_name.clone(), (data.clone(), shape.clone()));
        }}
        if name.ends_with("_quantized") && !f32.contains_key(name.as_str()) {{
            f32.insert(name.clone(), (data.clone(), shape.clone()));
        }}
        let import_name = format!("{{name}}_f32_import");
        if !f32.contains_key(&import_name) {{
            f32.insert(import_name, (data, shape));
        }}
    }}
    Ok(LoadedWeights {{ f32, i64 }})
}}

/// ONNX initializer names in this model ({count} tensors).
pub const PARAM_NAMES: &[&str] = &[
{names}
];
"#,
        count = all_names.len(),
        names = all_names
            .iter()
            .map(|n| format!("    {:?},", rust_str_lit(n)))
            .collect::<Vec<_>>()
            .join("\n"),
    )
}

fn emit_graph_rs(plan: &DecomposePlan) -> String {
    let mut e = Emitter::new();
    e.line("// AUTO-GENERATED by rlx-onnx-decompose — do not edit.");
    e.line("");
    e.line("#![allow(");
    e.line("    non_snake_case,");
    e.line("    unused_mut,");
    e.line("    unused_imports,");
    e.line("    dead_code,");
    e.line("    clippy::unnecessary_cast,");
    e.line("    clippy::manual_is_multiple_of,");
    e.line("    clippy::vec_init_then_push,");
    e.line("    clippy::clone_on_copy");
    e.line(")]");
    e.line("");
    e.line("use std::collections::HashMap;");
    e.line("");
    e.line("use anyhow::{Context, Result};");
    e.line("use rlx_ir::hir::{HirMut, HirNodeId};");
    e.line("use rlx_ir::op::{Activation, BinaryOp, CmpOp, ReduceOp};");
    e.line("use rlx_ir::{DType, HirGraphExt, HirModule, Shape};");
    e.line("use rlx_ir::shape;");
    e.line("use serde_json;");
    e.line("");
    e.line("/// Dynamic dimension bindings used when lowering ONNX.");
    e.line("#[derive(Debug, Clone)]");
    e.line("pub struct GraphOptions {");
    e.block(|e| {
        e.line("pub sequence_length: usize,");
        e.line("pub max_waveform_samples: usize,");
    });
    e.line("}");
    e.line("");
    e.line("impl Default for GraphOptions {");
    e.block(|e| {
        e.line("fn default() -> Self {");
        e.block(|e| {
            e.line("Self {");
            e.block(|e| {
                e.line("sequence_length: 128,");
                e.line("max_waveform_samples: 24_000,");
            });
            e.line("}");
        });
        e.line("}");
    });
    e.line("}");
    e.line("");
    e.line("struct Builder {");
    e.block(|e| {
        e.line("hir: HirModule,");
        e.line("params: HashMap<String, Vec<f32>>,");
        e.line("i64_params: HashMap<String, Vec<i64>>,");
        e.line("env: HashMap<String, HirNodeId>,");
    });
    e.line("}");
    e.line("");
    e.line("impl Builder {");
    e.block(|e| {
        e.line(format!(
            "fn new() -> Self {{ Self {{ hir: HirModule::new({}), params: HashMap::new(), i64_params: HashMap::new(), env: HashMap::new() }} }}",
            rust_str_lit(&plan.module_name)
        ));
        e.line("fn m(&mut self) -> HirMut<'_> { HirMut::new(&mut self.hir) }");
        e.line("fn bind(&mut self, name: &str, id: HirNodeId) { self.env.insert(name.to_string(), id); }");
        e.line("fn tensor(&self, name: &str) -> Result<HirNodeId> {");
        e.block(|e| {
            e.line("self.env.get(name).copied().with_context(|| format!(\"tensor {:?}\", name))");
        });
        e.line("}");
        e.line("fn bind_param(&mut self, key: &str, shape: &[usize], data: Vec<f32>) -> HirNodeId {");
        e.block(|e| {
            e.line("let id = HirMut::new(&mut self.hir).param(key, Shape::new(shape, DType::F32));");
            e.line("self.params.insert(key.to_string(), data);");
            e.line("id");
        });
        e.line("}");
        e.line("fn bind_param_i64(&mut self, key: &str, shape: &[usize], data: Vec<i64>) -> HirNodeId {");
        e.block(|e| {
            e.line("let id = HirMut::new(&mut self.hir).param(key, Shape::new(shape, DType::I64));");
            e.line("self.i64_params.insert(key.to_string(), data);");
            e.line("id");
        });
        e.line("}");
        e.line("fn i64_data(&self, name: &str) -> Result<&[i64]> {");
        e.block(|e| {
            e.line("self.i64_params.get(name).map(|v| v.as_slice()).with_context(|| format!(\"i64 tensor {:?}\", name))");
        });
        e.line("}");
    });
    e.line("}");
    e.line("");
    e.line(
        "fn reshape_dims_from_i64(numel: usize, raw: &[i64], input_dims: &[usize]) -> Vec<i64> {",
    );
    e.block(|e| {
        e.line("let mut dims: Vec<i64> = raw.to_vec();");
        e.line("// ONNX: 0 means copy from the corresponding input dimension.");
        e.line("for (i, d) in dims.iter_mut().enumerate() {");
        e.block(|e| {
            e.line("if *d == 0 {");
            e.block(|e| {
                e.line("if let Some(&id) = input_dims.get(i) { *d = id as i64; }");
            });
            e.line("}");
        });
        e.line("}");
        e.line("if let Some(neg) = dims.iter().position(|&d| d < 0) {");
        e.block(|e| {
            e.line("let known: i64 = dims.iter().filter(|&&d| d > 0).product();");
            e.line("let known = known.max(1) as usize;");
            e.line("dims[neg] = (numel / known.max(1)) as i64;");
        });
        e.line("}");
        e.line("dims");
    });
    e.line("}");
    e.line("");
    e.line("/// Build HIR + param map from decomposed ONNX.");
    e.line("pub fn build_hir(");
    e.line("    weights: &crate::weights::LoadedWeights,");
    e.line("    opts: &GraphOptions,");
    e.line(") -> Result<(HirModule, HashMap<String, Vec<f32>>)> {");
    e.block(|e| {
        e.line("let mut b = Builder::new();");
        e.line("");

        for io in &plan.manifest.inputs {
            let dtype = dtype_rust(&io.meta.dtype);
            let shape = shape_rust(&io.meta.shape, "opts");
            e.line(format!(
                "let {}_id = {{ let mut m = HirMut::new(&mut b.hir); m.input({}, Shape::new(&{}, {})) }};",
                sanitize_ident(&io.name),
                rust_str_lit(&io.name),
                shape,
                dtype
            ));
            e.line(format!("b.bind({}, {}_id);", rust_str_lit(&io.name), sanitize_ident(&io.name)));
        }
        e.line("");

        let init_names: std::collections::HashSet<_> = plan
            .params
            .keys()
            .chain(plan.i64_params.keys())
            .map(String::as_str)
            .collect();
        for node in &plan.nodes {
            emit_node(e, node, &init_names, plan);
        }
        e.line("");
        e.line("let mut outs = Vec::new();");
        for o in &plan.manifest.outputs {
            e.line(format!(
                "outs.push(b.tensor({})?);",
                rust_str_lit(&o.name)
            ));
        }
        e.line("{ let mut m = HirMut::new(&mut b.hir); m.set_outputs(outs); }");
        e.line("Ok((b.hir, b.params))");
    });
    e.line("}");
    e.line("");
    emit_shape_helper(&mut e);
    e.into_string()
}

fn emit_shape_helper(e: &mut Emitter) {
    e.line("fn resolve_dim(v: &serde_json::Value, opts: &GraphOptions) -> usize {");
    e.block(|e| {
        e.line("match v {");
        e.block(|e| {
            e.line("serde_json::Value::Number(n) => {");
            e.line("let v = n.as_u64().unwrap_or(0) as usize;");
            e.line("if v == 0 { opts.sequence_length } else { v }");
            e.line("},");
            e.line("serde_json::Value::String(s) => match s.as_str() {");
            e.block(|e| {
                e.line("\"sequence_length\" => opts.sequence_length,");
                e.line("\"num_samples\" => opts.max_waveform_samples,");
                e.line("\"?\" => opts.sequence_length,");
                e.line("_ if s.starts_with(\"unk__\") => opts.sequence_length,");
                e.line("_ => 1,");
            });
            e.line("},");
            e.line("_ => 1,");
        });
        e.line("}");
    });
    e.line("}");
    e.line("");
    e.line("fn shape_from_meta(meta: &serde_json::Value, opts: &GraphOptions) -> Shape {");
    e.block(|e| {
        e.line("let obj = meta.as_object().expect(\"shape meta\");");
        e.line("let shape_v = obj.get(\"shape\").expect(\"shape\");");
        e.line("let dtype_s = obj.get(\"dtype\").and_then(|d| d.as_str()).unwrap_or(\"f32\");");
        e.line("let dims: Vec<usize> = match shape_v {");
        e.block(|e| {
            e.line(
                "serde_json::Value::Array(a) => a.iter().map(|d| resolve_dim(d, opts)).collect(),",
            );
            e.line("_ => vec![1],");
        });
        e.line("};");
        e.line("let dtype = match dtype_s {");
        e.block(|e| {
            e.line("\"f32\" => DType::F32,");
            e.line("\"i64\" => DType::I64,");
            e.line("\"i32\" => DType::I32,");
            e.line("\"bool\" => DType::Bool,");
            e.line("_ => DType::F32,");
        });
        e.line("};");
        e.line("Shape::new(&dims, dtype)");
    });
    e.line("}");
    e.line("");
    e.line("/// Channel axis: the dimension of `like` whose size matches the rank-1 param length.");
    e.line(
        "fn channel_axis_for_param(m: &mut HirMut, param: HirNodeId, like: HirNodeId) -> usize {",
    );
    e.block(|e| {
        e.line("let c = m.shape(param).dim(0).unwrap_static();");
        e.line("let like_sh = m.shape(like);");
        e.line("for (i, d) in like_sh.dims().iter().enumerate() {");
        e.line("if d.unwrap_static() == c { return i; }");
        e.line("}");
        e.line("if like_sh.rank() >= 2 { like_sh.rank() - 1 } else { 0 }");
    });
    e.line("}");
    e.line("");
    e.line("/// Reshape a rank-1 scale/bias vector for channel-wise broadcast on `like`.");
    e.line("fn broadcast_1d_param(m: &mut HirMut, param: HirNodeId, like: HirNodeId, axis: usize) -> HirNodeId {");
    e.block(|e| {
        e.line("let rank = m.shape(like).rank().max(1);");
        e.line("let c = m.shape(param).dim(0).unwrap_static() as i64;");
        e.line("let mut bc = vec![1i64; rank];");
        e.line("bc[axis.min(rank.saturating_sub(1))] = c;");
        e.line("m.reshape_(param, bc)");
    });
    e.line("}");
    e.line("");
    e.line("fn broadcast_param_channels(m: &mut HirMut, param: HirNodeId, like: HirNodeId) -> HirNodeId {");
    e.block(|e| {
        e.line("let axis = channel_axis_for_param(m, param, like);");
        e.line("broadcast_1d_param(m, param, like, axis)");
    });
    e.line("}");
    e.line("");
    e.line("fn inst_norm_reduce_axes(rank: usize, channel_axis: usize) -> Vec<usize> {");
    e.block(|e| {
        e.line("(0..rank).filter(|&i| i != 0 && i != channel_axis).collect()");
    });
    e.line("}");
    e.line("");
    e.line(
        "fn binary_infer(m: &mut HirMut, op: BinaryOp, a: HirNodeId, b: HirNodeId, _site: &str) -> HirNodeId {",
    );
    e.block(|e| {
        e.line("binary_infer_inner(m, op, a, b)");
    });
    e.line("}");
    e.line("");
    e.line(
        "fn binary_infer_inner(m: &mut HirMut, op: BinaryOp, a: HirNodeId, b: HirNodeId) -> HirNodeId {",
    );
    e.block(|e| {
        e.line("let mut a_in = a;");
        e.line("let mut b_in = b;");
        e.line("let sa0 = m.shape(a_in).clone();");
        e.line("let sb0 = m.shape(b_in).clone();");
        e.line("if (sa0.rank() == 0 || sa0.rank() == 1) && sb0.rank() >= 2 {");
        e.line("  let a1 = if sa0.rank() == 0 { m.reshape_(a_in, vec![1]) } else { a_in };");
        e.line("  a_in = broadcast_param_channels(m, a1, b_in);");
        e.line("} else if (sb0.rank() == 0 || sb0.rank() == 1) && sa0.rank() >= 2 {");
        e.line("  let b1 = if sb0.rank() == 0 { m.reshape_(b_in, vec![1]) } else { b_in };");
        e.line("  b_in = broadcast_param_channels(m, b1, a_in);");
        e.line("}");
        e.line("let sa = m.shape(a_in).clone();");
        e.line("let sb = m.shape(b_in).clone();");
        e.line("if let Ok(sh) = shape::binary_shape(&sa, &sb) {");
        e.line("  return m.add_node(rlx_ir::Op::Binary(op), vec![a_in, b_in], sh);");
        e.line("}");
        e.line("// Special case: flatten([B,C,L]) -> [B,1,C*L] then add per-channel bias [1,1,C].");
        e.line("if sa.rank() == 3 && sb.rank() == 3");
        e.line("  && sa.dim(1).unwrap_static() == 1");
        e.line("  && sb.dim(0).unwrap_static() == 1");
        e.line("  && sb.dim(1).unwrap_static() == 1");
        e.line("  && sa.dim(2).unwrap_static() % sb.dim(2).unwrap_static() == 0 {");
        e.line("  let bsz = sa.dim(0).unwrap_static();");
        e.line("  let c = sb.dim(2).unwrap_static();");
        e.line("  let l = sa.dim(2).unwrap_static() / c;");
        e.line("  let dt = sa.dtype();");
        e.line("  let a3 = m.reshape_(a_in, vec![bsz as i64, c as i64, l as i64]);");
        e.line("  let b3 = m.reshape_(b_in, vec![1, c as i64, 1]);");
        e.line("  let y3 = m.add_node(rlx_ir::Op::Binary(op), vec![a3, b3], Shape::new(&[bsz, c, l], dt));");
        e.line("  return m.reshape_(y3, vec![bsz as i64, 1, (c * l) as i64]);");
        e.line("}");
        e.line("// Special case: [B,2C,L] + [B,C,L] (concat-style broadcast).");
        e.line("if sa.rank() == sb.rank() && sa.rank() == 3");
        e.line("  && sa.dim(0).unwrap_static() == sb.dim(0).unwrap_static()");
        e.line("  && sa.dim(2).unwrap_static() == sb.dim(2).unwrap_static()");
        e.line("  && sa.dim(1).unwrap_static() == 2 * sb.dim(1).unwrap_static() {");
        e.line("  let bsz = sa.dim(0).unwrap_static();");
        e.line("  let c = sb.dim(1).unwrap_static();");
        e.line("  let l = sa.dim(2).unwrap_static();");
        e.line("  let dt = sa.dtype();");
        e.line("  let b_rep = m.reshape_(b_in, vec![bsz as i64, c as i64, 1, l as i64]);");
        e.line("  let b_rep = m.add_node(rlx_ir::Op::Concat { axis: 3 }, vec![b_rep.clone(), b_rep], Shape::new(&[bsz, c, 2, l], dt));");
        e.line("  b_in = m.reshape_(b_rep, vec![bsz as i64, (2 * c) as i64, l as i64]);");
        e.line("  let sh = shape::binary_shape(m.shape(a_in), m.shape(b_in)).unwrap_or(sa.clone());");
        e.line("  return m.add_node(rlx_ir::Op::Binary(op), vec![a_in, b_in], sh);");
        e.line("}");
        e.line("let sh = if sa.rank() >= sb.rank() { sa } else { sb };");
        e.line("m.add_node(rlx_ir::Op::Binary(op), vec![a_in, b_in], sh)");
    });
    e.line("}");
    e.line("");
    // Abramowitz–Stegun 7.1.26 erf (same as rlx-onnx-import lower_erf).
    e.line("fn hir_erf(b: &mut Builder, x: HirNodeId, site: &str) -> HirNodeId {");
    e.block(|e| {
        e.line("let s = { let m = HirMut::new(&mut b.hir); m.shape(x).clone() };");
        e.line("let sc = |b: &mut Builder, tag: &str, v: f32| -> HirNodeId {");
        e.line("  let key = format!(\"__erf_{tag}__/{site}\");");
        e.line("  b.bind_param(&key, &[1], vec![v])");
        e.line("};");
        e.line("let one = sc(b, \"one\", 1.0);");
        e.line("let p = sc(b, \"p\", 0.327_591_1);");
        e.line("let a5 = sc(b, \"a5\", 1.061_405_4);");
        e.line("let a0 = sc(b, \"a0\", -1.453_152_1);");
        e.line("let a1 = sc(b, \"a1\", 1.421_413_8);");
        e.line("let a2 = sc(b, \"a2\", -0.284_496_72);");
        e.line("let a3 = sc(b, \"a3\", 0.254_829_6);");
        e.line("let tiny = sc(b, \"tiny\", 1e-20);");
        e.line("let mut m = HirMut::new(&mut b.hir);");
        e.line("let ax = m.add_node(rlx_ir::Op::Activation(Activation::Abs), vec![x], s.clone());");
        e.line("let pax = m.add_node(rlx_ir::Op::Binary(BinaryOp::Mul), vec![ax, p], s.clone());");
        e.line("let denom = m.add_node(rlx_ir::Op::Binary(BinaryOp::Add), vec![pax, one], s.clone());");
        e.line("let t = m.add_node(rlx_ir::Op::Binary(BinaryOp::Div), vec![one, denom], s.clone());");
        e.line("let mut acc = a5;");
        e.line("for coef in [a0, a1, a2, a3] {");
        e.line("  let tm = m.add_node(rlx_ir::Op::Binary(BinaryOp::Mul), vec![t, acc], s.clone());");
        e.line("  acc = m.add_node(rlx_ir::Op::Binary(BinaryOp::Add), vec![tm, coef], s.clone());");
        e.line("}");
        e.line("let poly = m.add_node(rlx_ir::Op::Binary(BinaryOp::Mul), vec![t, acc], s.clone());");
        e.line("let x2 = m.add_node(rlx_ir::Op::Binary(BinaryOp::Mul), vec![x, x], s.clone());");
        e.line("let negx2 = m.add_node(rlx_ir::Op::Activation(Activation::Neg), vec![x2], s.clone());");
        e.line("let ex = m.add_node(rlx_ir::Op::Activation(Activation::Exp), vec![negx2], s.clone());");
        e.line("let pe = m.add_node(rlx_ir::Op::Binary(BinaryOp::Mul), vec![poly, ex], s.clone());");
        e.line("let y = m.add_node(rlx_ir::Op::Binary(BinaryOp::Sub), vec![one, pe], s.clone());");
        e.line("let x2t = m.add_node(rlx_ir::Op::Binary(BinaryOp::Add), vec![x2, tiny], s.clone());");
        e.line("let inv = m.add_node(rlx_ir::Op::Activation(Activation::Rsqrt), vec![x2t], s.clone());");
        e.line("let sign = m.add_node(rlx_ir::Op::Binary(BinaryOp::Mul), vec![x, inv], s.clone());");
        e.line("m.add_node(rlx_ir::Op::Binary(BinaryOp::Mul), vec![sign, y], s)");
    });
    e.line("}");
}

fn emit_node(
    e: &mut Emitter,
    node: &BundleNode,
    inits: &std::collections::HashSet<&str>,
    plan: &DecomposePlan,
) {
    let comment = format!("// {} ({})", node.name, node.op);
    e.line(&comment);

    for name in &node.inputs {
        if inits.contains(name.as_str()) && !node.outputs.is_empty() {
            if let Some(shape) = plan.init_shapes.get(name) {
                // RLX has no rank-0; promote ONNX scalar `dims=[]` to `[1]`
                // (same as rlx-onnx-import lowerer) so Binary broadcast works.
                let shape: &[usize] = if shape.is_empty() { &[1] } else { shape };
                let shape_lit = format!(
                    "&[{}]",
                    shape
                        .iter()
                        .map(|d| d.to_string())
                        .collect::<Vec<_>>()
                        .join(", ")
                );
                let is_i64 = plan.i64_params.contains_key(name.as_str());
                e.line(format!("if !b.env.contains_key({}) {{", rust_str_lit(name)));
                e.block(|e| {
                    if is_i64 {
                        e.line(format!(
                            "let (data, _) = weights.i64.get({}).with_context(|| format!(\"i64 weight {{}}\", {}))?;",
                            rust_str_lit(name),
                            rust_str_lit(name),
                        ));
                        e.line(format!(
                            "let id = b.bind_param_i64({}, {}, data.clone());",
                            rust_str_lit(name),
                            shape_lit,
                        ));
                    } else {
                        e.line(format!(
                            "let (data, _) = weights.f32.get({}).with_context(|| format!(\"weight {{}}\", {}))?;",
                            rust_str_lit(name),
                            rust_str_lit(name),
                        ));
                        e.line(format!(
                            "let id = b.bind_param({}, {}, data.clone());",
                            rust_str_lit(name),
                            shape_lit,
                        ));
                    }
                    e.line(format!("b.bind({}, id);", rust_str_lit(name)));
                });
                e.line("}");
            }
        }
    }

    if node.op == "DynamicQuantizeLinear" {
        for (oi, out_name) in node.outputs.iter().enumerate() {
            let out_ident = format!("n_{}_{}", sanitize_ident(out_name), oi);
            for line in
                rlx_onnx_import::emit_codegen::emit_dynamic_quant_output(node, oi, &out_ident)
            {
                e.line(line);
            }
            e.line(format!(
                "b.bind({}, {});",
                rust_str_lit(out_name),
                out_ident
            ));
        }
    } else if node.op == "TopK" && node.outputs.len() >= 2 {
        let val_out = &node.outputs[0];
        let idx_out = &node.outputs[1];
        let val_ident = format!("n_{}", sanitize_ident(val_out));
        let idx_ident = format!("n_{}", sanitize_ident(idx_out));
        for line in rlx_onnx_import::emit_codegen::emit_topk(node, &val_ident, &idx_ident) {
            e.line(line);
        }
        e.line(format!("b.bind({}, {});", rust_str_lit(val_out), val_ident));
        e.line(format!("b.bind({}, {});", rust_str_lit(idx_out), idx_ident));
    } else if node.op == "Shape" && !node.inputs.is_empty() && !node.outputs.is_empty() {
        let out = &node.outputs[0];
        let out_ident = format!("n_{}", sanitize_ident(out));
        // Bind under the ONNX output name so later Slice/Concat/Reshape can fold i64 vectors.
        e.line(format!(
            "let {out_ident} = {{ let x = b.tensor({})?; let mut m = HirMut::new(&mut b.hir); \
             let s = m.shape(x).clone(); \
             let data: Vec<i64> = (0..s.rank()).map(|i| s.dim(i).unwrap_static() as i64).collect(); \
             b.bind_param_i64({}, &[data.len()], data) }};",
            rust_str_lit(&node.inputs[0]),
            rust_str_lit(out),
        ));
        e.line(format!("b.bind({}, {});", rust_str_lit(out), out_ident));
    } else if node.op == "Slice"
        && node.inputs.len() >= 3
        && !node.outputs.is_empty()
        && plan.i64_params.contains_key(node.inputs[1].as_str())
        && plan.i64_params.contains_key(node.inputs[2].as_str())
    {
        let out = &node.outputs[0];
        let out_ident = format!("n_{}", sanitize_ident(out));
        let starts = &plan.i64_params[&node.inputs[1]];
        let ends = &plan.i64_params[&node.inputs[2]];
        let axes = node
            .inputs
            .get(3)
            .and_then(|n| plan.i64_params.get(n.as_str()))
            .cloned()
            .unwrap_or_else(|| vec![0]);
        let axis = axes.first().copied().unwrap_or(0).max(0) as usize;
        let start = starts.first().copied().unwrap_or(0).max(0) as usize;
        let end = ends.first().copied().unwrap_or(start as i64 + 1);
        // Prefer constant-fold when slicing an i64 shape vector (SVTR reshape path).
        e.line(format!(
            "let {out_ident} = {{ \
             let src = b.i64_data({}).ok().map(|s| s.to_vec()); \
             if let Some(data) = src {{ \
             let end_i: i64 = {end}; \
             let dim = data.len(); \
             let end = if end_i < 0 {{ dim.saturating_sub((-end_i) as usize) }} else {{ (end_i as usize).min(dim) }}; \
             let sliced = data.get({start}..end).unwrap_or(&[]).to_vec(); \
             b.bind_param_i64({}, &[sliced.len().max(1)], if sliced.is_empty() {{ vec![0] }} else {{ sliced }}) \
             }} else {{ \
             let x = b.tensor({})?; let mut m = HirMut::new(&mut b.hir); \
             let dim = m.shape(x).dim({axis}).unwrap_static(); \
             let end_i: i64 = {end}; \
             let end = if end_i < 0 {{ dim.saturating_sub((-end_i) as usize) }} else {{ (end_i as usize).min(dim) }}; \
             let len = end.saturating_sub({start}).max(1); \
             m.narrow_(x, {axis}, {start}, len) }} }};",
            rust_str_lit(&node.inputs[0]),
            rust_str_lit(out),
            rust_str_lit(&node.inputs[0]),
        ));
        e.line(format!("b.bind({}, {});", rust_str_lit(out), out_ident));
    } else if node.op == "Concat" && !node.outputs.is_empty() {
        // Constant-fold Concat of i64 shape pieces when every input has i64 data.
        let out = &node.outputs[0];
        let out_ident = format!("n_{}", sanitize_ident(out));
        let axis = node.attrs.get("axis").and_then(|v| v.as_i64()).unwrap_or(0);
        if axis == 0 {
            let gets: String = node
                .inputs
                .iter()
                .map(|n| format!("b.i64_data({}).ok().map(|s| s.to_vec())", rust_str_lit(n)))
                .collect::<Vec<_>>()
                .join(", ");
            let prefetch: String = node
                .inputs
                .iter()
                .enumerate()
                .map(|(i, n)| format!("let __t_{out_ident}_{i} = b.tensor({})?;", rust_str_lit(n)))
                .collect::<Vec<_>>()
                .join(" ");
            let ids: String = (0..node.inputs.len())
                .map(|i| format!("__t_{out_ident}_{i}"))
                .collect::<Vec<_>>()
                .join(", ");
            e.line(format!(
                "let {out_ident} = {{ \
                 let parts: Vec<Option<Vec<i64>>> = vec![{gets}]; \
                 if parts.iter().all(|p| p.is_some()) {{ \
                   let mut data = Vec::new(); \
                   for p in parts {{ data.extend(p.unwrap()); }} \
                   b.bind_param_i64({}, &[data.len()], data) \
                 }} else {{ \
                   {prefetch} \
                   let mut m = HirMut::new(&mut b.hir); \
                   m.add_node(rlx_ir::Op::Concat {{ axis: 0 }}, vec![{ids}], Shape::new(&[{}], DType::I64)) \
                 }} }};",
                rust_str_lit(out),
                node.inputs.len().max(1),
            ));
            e.line(format!("b.bind({}, {});", rust_str_lit(out), out_ident));
        } else {
            for line in rlx_onnx_import::emit_codegen::emit_node_body(node, &out_ident) {
                e.line(line);
            }
            e.line(format!("b.bind({}, {});", rust_str_lit(out), out_ident));
        }
    } else if (node.op == "Identity" || node.op == "Cast")
        && !node.outputs.is_empty()
        && !node.inputs.is_empty()
    {
        // Alias i64 shape vectors through Identity/Cast so later Reshape can fold.
        let out = &node.outputs[0];
        let out_ident = format!("n_{}", sanitize_ident(out));
        let inp = &node.inputs[0];
        e.line(format!(
            "let {out_ident} = {{ \
             if let Some(data) = b.i64_data({}).ok().map(|s| s.to_vec()) {{ \
               b.bind_param_i64({}, &[data.len()], data) \
             }} else {{ \
               b.tensor({})? \
             }} }};",
            rust_str_lit(inp),
            rust_str_lit(out),
            rust_str_lit(inp),
        ));
        e.line(format!("b.bind({}, {});", rust_str_lit(out), out_ident));
    } else if (node.op == "Squeeze" || node.op == "Unsqueeze")
        && !node.outputs.is_empty()
        && !node.inputs.is_empty()
    {
        let out = &node.outputs[0];
        let out_ident = format!("n_{}", sanitize_ident(out));
        let inp = &node.inputs[0];
        if node.op == "Squeeze" {
            let axes: Vec<i64> = node
                .attrs
                .get("axes")
                .and_then(|v| v.as_array())
                .map(|a| a.iter().filter_map(|x| x.as_i64()).collect())
                .unwrap_or_default();
            let axes_lit = format!(
                "[{}]",
                axes.iter()
                    .map(|a| a.to_string())
                    .collect::<Vec<_>>()
                    .join(", ")
            );
            e.line(format!(
                "let {out_ident} = {{ \
                 if let Some(data) = b.i64_data({}).ok().map(|s| s.to_vec()) {{ \
                   b.bind_param_i64({}, &[data.len().max(1)], if data.is_empty() {{ vec![0] }} else {{ data }}) \
                 }} else {{ \
                   let x = b.tensor({})?; let mut m = HirMut::new(&mut b.hir); \
                   let sh = m.shape(x).clone(); \
                   let axes: &[i64] = &{axes_lit}; \
                   let mut dims: Vec<i64> = Vec::new(); \
                   for i in 0..sh.rank() {{ \
                     let d = sh.dim(i).unwrap_static() as i64; \
                     let axis_i = i as i64; \
                     let drop = if axes.is_empty() {{ d == 1 }} else {{ axes.contains(&axis_i) && d == 1 }}; \
                     if !drop {{ dims.push(d); }} \
                   }} \
                   if dims.is_empty() {{ dims.push(1); }} \
                   m.reshape_(x, dims) \
                 }} }};",
                rust_str_lit(inp),
                rust_str_lit(out),
                rust_str_lit(inp),
            ));
        } else {
            // Unsqueeze: wrap scalar i64 as length-1 vector.
            e.line(format!(
                "let {out_ident} = {{ \
                 if let Some(data) = b.i64_data({}).ok().map(|s| s.to_vec()) {{ \
                   let v = if data.is_empty() {{ 0 }} else {{ data[0] }}; \
                   b.bind_param_i64({}, &[1], vec![v]) \
                 }} else {{ \
                   let x = b.tensor({})?; let sh = shape_from_meta({}, opts); \
                   let dims: Vec<i64> = sh.dims().iter().map(|d| d.unwrap_static() as i64).collect(); \
                   let mut m = HirMut::new(&mut b.hir); m.reshape_(x, dims) \
                 }} }};",
                rust_str_lit(inp),
                rust_str_lit(out),
                rust_str_lit(inp),
                node.output_meta
                    .first()
                    .map(|m| format!("&serde_json::json!({m})"))
                    .unwrap_or_else(|| {
                        "&serde_json::json!({\"dtype\":\"i64\",\"shape\":[1]})".into()
                    }),
            ));
        }
        e.line(format!("b.bind({}, {});", rust_str_lit(out), out_ident));
    } else if node.op == "Reshape" && node.inputs.len() >= 2 && !node.outputs.is_empty() {
        let out = &node.outputs[0];
        let out_ident = format!("n_{}", sanitize_ident(out));
        let meta_fallback = node
            .output_meta
            .first()
            .map(|m| format!("&serde_json::json!({})", m))
            .unwrap_or_else(|| "&serde_json::json!({\"dtype\":\"f32\",\"shape\":[1]})".into());
        e.line(format!(
            "let {out_ident} = {{ \
             let raw_shape = b.i64_data({}).ok().map(|s| s.to_vec()); \
             let x = b.tensor({})?; \
             if let Some(raw) = raw_shape {{ \
               let mut m = HirMut::new(&mut b.hir); \
               let in_s = m.shape(x).clone(); \
               let numel = in_s.num_elements().unwrap_or(1); \
               let input_dims: Vec<usize> = (0..in_s.rank()).map(|i| in_s.dim(i).unwrap_static()).collect(); \
               let dims = reshape_dims_from_i64(numel, &raw, &input_dims); \
               m.reshape_(x, dims) \
             }} else {{ \
               let sh = shape_from_meta({meta_fallback}, opts); \
               let dims: Vec<i64> = sh.dims().iter().map(|d| d.unwrap_static() as i64).collect(); \
               let mut m = HirMut::new(&mut b.hir); m.reshape_(x, dims) \
             }} }};",
            rust_str_lit(&node.inputs[1]),
            rust_str_lit(&node.inputs[0]),
        ));
        e.line(format!("b.bind({}, {});", rust_str_lit(out), out_ident));
    } else {
        let out = node.outputs.first().map(String::as_str).unwrap_or("out");
        let out_ident = format!("n_{}", sanitize_ident(out));

        for line in rlx_onnx_import::emit_codegen::emit_node_body(node, &out_ident) {
            e.line(line);
        }

        if !node.outputs.is_empty() {
            e.line(format!("b.bind({}, {});", rust_str_lit(out), out_ident));
        }
    }
    e.line("");
}

fn emit_readme(plan: &DecomposePlan, weights: WeightsFormat) -> String {
    let wf = match weights {
        WeightsFormat::Safetensors => "model.safetensors",
        WeightsFormat::Gguf => "model.gguf (+ model.safetensors)",
    };
    format!(
        r#"# {0} (RLX native, decomposed from ONNX)

Auto-generated from `{1}`.

## Layout

- `src/graph.rs` — hand-lowered ONNX graph as RLX HIR builder
- `src/weights.rs` — load `{2}`
- `weights/` — exported tensors
- `decompose_report.json` — op coverage / unsupported ops

## Usage

```rust
use {0}::{{compile, GraphOptions}};
use rlx_runtime::Device;

let compiled = compile(
    Device::Cpu,
    std::path::Path::new("weights"),
    &GraphOptions::default(),
)?;
```

## Coverage

- Lowered nodes: {3}
- Skipped: {4}
- Unsupported ops: {5:?}

Extend `graph.rs` (or re-run decompose after extending `rlx-onnx-import`) for missing ops.
"#,
        plan.crate_name,
        plan.source_onnx.display(),
        wf,
        plan.import_report.lowered,
        plan.import_report.skipped,
        plan.import_report.unsupported,
    )
}

fn rust_str_lit(s: &str) -> String {
    format!("{s:?}")
}

fn sanitize_ident(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
        } else {
            out.push('_');
        }
        if out.len() > 64 {
            break;
        }
        let _ = i;
    }
    if out.is_empty() || out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out = format!("t_{out}");
    }
    out
}

fn dtype_rust(s: &str) -> &'static str {
    match s {
        "f32" => "DType::F32",
        "i64" => "DType::I64",
        "i32" => "DType::I32",
        "bool" => "DType::Bool",
        _ => "DType::F32",
    }
}

fn shape_rust(shape: &[serde_json::Value], opts: &str) -> String {
    let dims: Vec<String> = shape
        .iter()
        .map(|v| match v {
            serde_json::Value::Number(n) => n
                .as_u64()
                .map(|x| x.to_string())
                .unwrap_or_else(|| "1".into()),
            serde_json::Value::String(s) => match s.as_str() {
                "sequence_length" => format!("{opts}.sequence_length"),
                "num_samples" => format!("{opts}.max_waveform_samples"),
                "?" => "1".to_string(),
                other if other.starts_with("unk__") => "1".to_string(),
                other => format!("/* symbolic {other:?} */ 1"),
            },
            _ => "1".to_string(),
        })
        .collect();
    format!("[{}]", dims.join(", "))
}

#[allow(dead_code)]
fn meta_lit(meta: &serde_json::Value) -> String {
    format!("&serde_json::json!({})", meta)
}
