// RLX — versatile ML compiler + runtime.
// Copyright (C) 2026 Eugene Hauptmann, Nataliya Kosmyna.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Native RLX model generated from KittenTTS ONNX.
//!
//! Auto-generated by `rlx-onnx-decompose` — do not edit `graph.rs` by hand.

#![allow(clippy::type_complexity, clippy::too_many_arguments)]

pub mod alignment;
pub mod bundle_compile;
pub mod bundle_patches;
pub mod gpu_kernels;
pub mod kernels;
pub mod lstm;
pub mod opts;
pub mod probe_watch;
pub mod qmatmul;
pub mod random;
pub mod scatter;
pub mod weights;

#[cfg(feature = "generated-graph")]
pub mod graph;

pub use opts::GraphOptions;
pub use weights::load_weights;

/// Set a process environment variable (Rust 2024 `set_var` wrapper).
pub fn set_env_var<K: AsRef<std::ffi::OsStr>, V: AsRef<std::ffi::OsStr>>(key: K, value: V) {
    // SAFETY: compile paths and tests set env before graph build / worker threads.
    unsafe { std::env::set_var(key, value) }
}

#[cfg(feature = "generated-graph")]
pub use graph::build_hir;

/// Compile the decomposed graph on `device`.
///
/// When `weights/rlx_bundle/` (or `KITTEN_RLX_BUNDLE`) is present, lowers ONNX via
/// `rlx-onnx-import` (real LSTM/Resize lowers). Otherwise uses generated `graph.rs`.
pub fn compile(
    device: rlx_runtime::Device,
    weights_path: &std::path::Path,
    opts: &GraphOptions,
) -> anyhow::Result<rlx_runtime::CompiledGraph> {
    if let Some(bundle) = bundle_compile::bundle_dir_near_weights(weights_path) {
        return bundle_compile::compile_from_bundle(device, &bundle, opts);
    }
    #[cfg(feature = "generated-graph")]
    {
        crate::kernels::register_native_kernels();
        let weights = load_weights(weights_path)?;
        let graph_opts = graph::GraphOptions {
            sequence_length: opts.sequence_length,
            max_waveform_samples: opts.max_waveform_samples,
        };
        let (hir, params) = build_hir(&weights, &graph_opts)?;
        let compile_opts = rlx_runtime::CompileOptions::default();
        let mut compiled = rlx_runtime::Session::new(device)
            .compile_hir_with(hir, &compile_opts)
            .map_err(|e| anyhow::anyhow!("{0}", e))?;
        for (name, data) in params {
            compiled.set_param(name.as_str(), &data);
        }
        return Ok(compiled);
    }
    #[cfg(not(feature = "generated-graph"))]
    anyhow::bail!(
        "no rlx_bundle found under {} and crate built without `generated-graph` feature",
        weights_path.display()
    )
}

pub const WEIGHTS_FORMAT: &str = "safetensors";
